services:
  backend:
    container_name: backend_service
    hostname: backend
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      music_library:
        aliases: [backend]
    ports:
      - "3002:3002"   # host:container
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3002/health"]  # container port
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  frontend:
    container_name: frontend_service
    hostname: frontend_service
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    environment:
      # talk to backend via service name on the bridge network
      NUXT_PUBLIC_BACKEND_BASE: http://backend:3002
      NUXT_PUBLIC_API_BASE: http://backend:3002/api
      HOST: 0.0.0.0
      NITRO_PORT: 8075
      PORT: 8075
    ports:
      - "8075:8075"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8075/"]
      interval: 10s
      timeout: 3s
      retries: 20
    networks:
      music_library:
        aliases: [music_library_frontend]
    restart: unless-stopped

networks:
  music_library:
    name: music_library
    driver: bridge
