---

services:

  # Database Service
 
  # Vault (security core)
 
  # Backend API (Express + TS)
  backend:
    profiles:
      - default
      - backend
    container_name: backend_service
    hostname: backend
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    labels:
      - "category=backend"
    networks:
      music_library:
        aliases:
          - backend
    ports:
      - "3000:3002"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3002/health"]
      interval: 10s
      timeout: 3s
      retries: 20
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend (Nuxt 3)
  frontend:
    profiles: [default, frontend]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    hostname: frontend_service
    labels:
      - "category=frontend"
      - "stack=frontend"
      - "tier=app"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      NUXT_PUBLIC_API_BASE: http://localhost:${API_PORT}
      NITRO_PORT: ${WEB_PORT}
    volumes:
      - ./frontend:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${WEB_PORT}/"]
      interval: 10s
      timeout: 3s
      retries: 20
    networks:
      music_library:
        aliases: [music_library_frontend]
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:

networks:
  music_library:
    name: music_library
    driver: bridge
